services:
  traefik:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9000"
      - "--log.level=DEBUG"
      - "--accesslog=true"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - VALID_TOKEN=${VALID_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=9001"

  sd-service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/stable-diffusion-models:/models
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.entrypoints=web"
      - "traefik.http.routers.sd.rule=PathPrefix(`/`)"
      - "traefik.http.services.sd.loadbalancer.server.port=9002"
      - "traefik.http.middlewares.auth-middleware.forwardauth.address=http://localhost:9001/auth/validate"
      - "traefik.http.middlewares.auth-middleware.forwardauth.authResponseHeaders=X-Auth-User"
      - "traefik.http.routers.sd.middlewares=auth-middleware@docker"