services:
  traefik:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9000"
      - "--entrypoints.traefik.address=:8080"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/rawdata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=9001"
      - "traefik.http.services.auth.loadbalancer.server.scheme=http"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/auth/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  sd-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/stable-diffusion-models:/models
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.entrypoints=web"
      - "traefik.http.routers.sd.rule=PathPrefix(`/`)"
      - "traefik.http.services.sd.loadbalancer.server.port=9002"
      - "traefik.http.services.sd.loadbalancer.server.scheme=http"
      - "traefik.http.routers.sd.middlewares=chain-auth@file"
    restart: unless-stopped
