networks:
  sd_net:
    external: true
    name: sd_network

services:
  sd-service:
    build:
      context: .
    container_name: sd_service
    expose:
      - "9002"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/stable-diffusion-models:/models
    networks:
      - sd_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.rule=PathPrefix(`/imagine`)"
      - "traefik.http.routers.sd.middlewares=chain-auth@file,strip-imagine@file"
      - "traefik.http.services.sd.loadbalancer.server.port=9002"
      - "traefik.http.middlewares.strip-imagine.stripprefix.prefixes=/imagine"
    restart: unless-stopped
