networks:
  sd_network:
    driver: bridge

services:
  traefik:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    networks:
      - sd_network
    ports:
      - "9000:9000"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9000"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - sd_network
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=9001"

  sd-service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - RAY_ADDRESS=127.0.0.1:6379
      - RAY_SERVE_HTTP_OPTIONS={"host":"0.0.0.0","port":8000}
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/stable-diffusion-models:/models
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.entrypoints=web"
      - "traefik.http.routers.sd.rule=PathPrefix(`/`)"
      - "traefik.http.services.sd.loadbalancer.server.port=9002"
      - "traefik.http.middlewares.auth-middleware.forwardauth.address=http://auth:9001/auth/validate"
      - "traefik.http.middlewares.auth-middleware.forwardauth.authResponseHeaders=X-Auth-User"
      - "traefik.http.routers.sd.middlewares=auth-middleware@docker"
    ports:
      - "9002:9002"
      - "8000:8000"
      - "8265:8265"