services:
  traefik:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--log.level=DEBUG"
      - "--accesslog=true"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    network_mode: "host"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8001"

  sd-service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/stable-diffusion-models:/models
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.entrypoints=web"
      - "traefik.http.routers.sd.rule=PathPrefix(`/`)"
      - "traefik.http.services.sd.loadbalancer.server.port=8000"

networks:
  sd_network:
    driver: bridge
    name: xpu_ray_sd_network