http:
  middlewares:
    global-limit:
      rateLimit:
        average: 10
        burst: 25
        period: 1s

    ip-limit:
      rateLimit:
        average: 10
        burst: 25
        period: 1s
        sourceCriterion:
          ipStrategy:
            depth: 1

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 31536005
        stsIncludeSubdomains: true
        customResponseHeaders:
          X-Server: "SD-Proxy"
    
    # Uncomment  to enable CORS
    # cors-headers:
    #   headers:
    #     accessControlAllowOrigin: "*"
    #     accessControlAllowMethods: "*"
    #     accessControlAllowHeaders: "*"
    #     accessControlMaxAge: 3600
    
    chain-auth:
      chain:
        middlewares:
          - auth-forward@file
          - strip-imagine@file
          - global-limit
          - ip-limit
          - security-headers
          # - cors-headers    # Uncomment this line when enabling CORS
