api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":8000"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: sd_network

log:
  level: "DEBUG"