api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":9000"
    http:
      middlewares:
        - chain-auth

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: "DEBUG"