api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":8000"
    http:
      middlewares:
        - rate-limit@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: sd_network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m

log:
  level: "DEBUG"